import type { Metadata } from "next";
import { Anuphan,Gowun_Dodum } from "next/font/google";
import "./globals.css";


// For body text 
const anuphan = Anuphan({
  variable: "--font-anuphan",
  subsets: ["latin"],
});

// For title
const gowunDodum = Gowun_Dodum({
  variable: "--font-gowun-dodum",
  subsets: ["latin"],
  weight: "400"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gowunDodum.variable} ${anuphan.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
